[project]
name = "logdoc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain==1.2.6",
    "langchain-openai",
    "jupyterlab",
    "ipykernel",
    "pandas",
    "PyMuPDF4LLM",
    "langchain-community",
    "qdrant-client",
    "langchain-qdrant",
    "langchain-tavily",
    "python-dotenv",
]
